version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automerge"
    groups:
      test-deps:
        patterns:
          - "org.junit.jupiter*"
          - "org.mockito*"
          - "org.mockbukkit*"
          - "com.tngtech.archunit*"
          - "org.assertj*"
          - "org.junit.platform*"
      gradle-plugins:
        patterns:
          - "com.gradleup.shadow*"
          - "com.github.spotbugs*"
          - "checkstyle*"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
